In [1]:
import numpy as np
import pandas as pd

In [2]:
lista_de_centimetros = list(range(170, 190, 5))
altura_em_centimetros = np.array(lista_de_centimetros)

In [3]:
altura_em_metros = altura_em_centimetros / 100

In [5]:
lista_pesos = [70, 75, 80, 85]
pesos = np.array(lista_pesos)

In [6]:
imc = pesos / (altura_em_metros ** 2)

In [7]:
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
nd_financeiros = np.array(dados_financeiros)

In [8]:
nd_financeiros = nd_financeiros.transpose()
print("Segunda linha do array:", nd_financeiros[1, :])
print("Segunda coluna do array:", nd_financeiros[:, 1])

Segunda linha do array: [2500 2500 5500]
Segunda coluna do array: [1000 2500 3000 5000]


In [9]:
endividamento_total = (nd_financeiros[:, 0] + nd_financeiros[:, 1]) / nd_financeiros[:, 2]
print(endividamento_total)

[0.66666667 0.90909091 0.57142857 0.9375    ]


In [10]:
nd_financeiros[2, 2] = 10000
endividamento_total = (nd_financeiros[:, 0] + nd_financeiros[:, 1]) / nd_financeiros[:, 2]
print(endividamento_total)

[0.66666667 0.90909091 0.4        0.9375    ]


In [11]:
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
nd_financeiros = np.array(dados_financeiros)

print(nd_financeiros)

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [12]:
endividamento_total = (nd_financeiros[0] + nd_financeiros[1]) / nd_financeiros[2]
print(endividamento_total)

[0.66666667 0.90909091 0.57142857 0.9375    ]


In [13]:
nd_financeiros[2, 2] = 10000
endividamento_total = (nd_financeiros[0] + nd_financeiros[1]) / nd_financeiros[2]
print(endividamento_total)

[0.66666667 0.90909091 0.4        0.9375    ]


In [14]:
# correção do erro de digitação
nd_financeiros[2, 2] = 10000

# cálculo do endividamento total
endividamento_total = (nd_financeiros[:, 0] + nd_financeiros[:, 1]) / nd_financeiros[:, 2]

# imprimindo resultados
print(endividamento_total)

[5.5        1.16666667 1.15      ]


In [15]:
poi = np.random.randint(0, 10, size=(10,))

# i) Criando objeto bool_zero
bool_zero = poi == 0

# ii) Contando valores zero
count_zero = sum(bool_zero)

# iii) Criando objeto poi_nao_zero
poi_nao_zero = poi[~bool_zero]

In [16]:
np.random.seed(1234)
poi = np.random.poisson(3, 100)

# i)
bool_zero = poi == 0

# ii)
num_zeros = sum(bool_zero)

# iii)
poi_nao_zero = poi[~bool_zero]

In [17]:
np.random.seed(1234)
poi = np.random.poisson(3, 100)

# i)
bool_zero = (poi == 0)

In [18]:
np.random.seed(1234)
poi = np.random.poisson(3, 100)

# i)
bool_zero = (poi == 0)

# ii)
num_zeros = sum(bool_zero)

In [19]:
np.random.seed(1234)
poi = np.random.poisson(3, 100)

# i)
bool_zero = (poi == 0)

# iii)
poi_nao_zero = poi[~bool_zero]